### PR TITLE
Updated to Gradle=6.1.1, API=30, Kotlin and AndroidX ready

### PR DESCRIPTION
**Pull request by hdavid0510**
Current version is not usable on Android 10 or newer, as Android dropped support of menu button to call options menu. By targeting newest version, options menu is automatically implemented into actionbar, make menu accessible without menu button. In addition, it makes this app meets google play API targeting restriction, so that this app can be updated further.

**What's Changed:**
 - Notification implementation updated; build notification via `Notification.Builder`
 - Task list item layout has been edited to make sure it can be displayed without any problem inside new(as API targeted got higher) layout.
 - Gradle syntax fixed; removed all deprecated keywords and updated all dependencies.
 - Migrated to AndroidX
 - Ready to use Kotlin (but not converted current codes to Kotlin yet)

**NOTE:**
Version code and naming has not changed, so this should be checked before update to Google Play.

### CODE REVIEW

**Comment by aaronjwood** [comment]
Is this project dead? It'd be nice to see this merged and released.

**Comment by hdavid0510** [comment]
Wow, these fixes were things I was just _planned_ to do, but I was um... too lazy to get it done soon, and @aaronjwood you've already done it! Great work :)
Rather than this MR, your [#28](https://github.com/palo-m/androboinc/pull/28) is definitely the one that should be merged, thus closing this MR.

**Comment by hdavid0510** [comment]
BTW,

> Is this project dead? It'd be nice to see this merged and released.

I was also worried about this. My MR seems to be quite overdue without any noticable activities in this repo.

**Comment by aaronjwood** [comment]
> Wow, these fixes were things I was just _planned_ to do, but I was um... too lazy to get it done soon, and @aaronjwood you've already done it! Great work :)
> Rather than this MR, your [#28](https://github.com/palo-m/androboinc/pull/28) is definitely the one that should be merged, thus closing this MR.

No problem, thanks for all the work you did as well! I used your changes as the foundation :)

**Pull request closed without merging**
